# Храненит чувствительные данные, таких как пароли, ключи шифрования и API-токены
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
  labels:
    app: db # Метка на всех манифестах, касающихся СУБД
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= # base64 for 'password'
  MYSQL_PASSWORD: cGFzc3dvcmQ=      # base64 for 'password'
  DB_PASSWORD: cGFzc3dvcmQ=         # base64 for 'password'
  DB_USERNAME: dXNlcg==             # base64 for 'user'
  DB_USER: dXNlcg==                 # base64 for 'user'
  MYSQL_USER: dXNlcg==              # base64 for 'user'
