# Обеспечивает стабильную сетевую коммуникацию между компонентами приложений 
# в условиях динамически изменяющейся среды кластера
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: db
  labels:
    app: db # Метка на всех манифестах, касающихся СУБД
spec:
  ports:
    - port: 3306
  selector:
    app: db # Метка на всех манифестах, касающихся СУБД
