apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: librespeed
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: librespeed
    spec:
      initContainers:
        - name: migrate-db
          image: mysql:5.7
          command:
            - sh
            - -c
            - |
              until mysql -h mysql-headless.db.svc.cluster.local -u $DB_USERNAME -p$DB_PASSWORD -e "SELECT 1"; do
                echo "Waiting for mysql in namespace db..."
                sleep 5
              done
              echo "MySQL is ready"
              echo "Checking for database and table existence..."
              if mysql -h mysql-headless.db.svc.cluster.local -u $DB_USERNAME -p$DB_PASSWORD -e "USE librespeed; SELECT 1 FROM speedtest_users LIMIT 1;" ; then
                echo "Database and table exist. No migrations required."
              else
                echo "Database or table does not exist. Performing migrations..."
                mysql -h mysql-headless.db.svc.cluster.local -u $DB_USERNAME -p$DB_PASSWORD librespeed < /telemetry_mysql.sql
              fi
          envFrom:
          - configMapRef:
              name: librespeed-env
          - secretRef:
              name: librespeed-secret
          volumeMounts:
            - name: mysql-sql
              mountPath: /telemetry_mysql.sql
              subPath: telemetry_mysql.sql
      imagePullSecrets:
        - name: registrysecret
      containers:
      - name: librespeed
        image: registry.rebrainme.com/workshops/middle/kubernetes-local/newplatform_autochecks/speedtest:5.3
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: librespeed-env
          - secretRef:
              name: librespeed-secret
        volumeMounts:
          - name: servers-volume
            mountPath: /servers.json
            subPath: servers.json
      volumes:
      - name: servers-volume
        configMap:
          name: librespeed-servers
      - name: mysql-sql
        configMap:
          name: mysql-sql
