# Храненит чувствительные данные, таких как пароли, ключи шифрования и API-токены
apiVersion: v1
kind: Secret
metadata:
  name: librespeed-secret
  namespace: final
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ= # base64 for 'password'
  DB_USER: dXNlcg==         # base64 for 'user'
  DB_USERNAME: dXNlcg==     # base64 for 'user'
