# Описывает, как создавать и управлять набором Pod’ов
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed # Имя деплоймента
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed # Метка на всех манифестах, касающихся приложения
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: librespeed # Метка на всех манифестах, касающихся приложения
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: librespeed # Метка на всех манифестах, касающихся приложения
    spec:
      initContainers:
        - name: migrate-db
          image: mysql:8.0 # последняя версия MySQL, доступная для Ubuntu 22.04
          command:
            - sh
            - -c
            - |
              until mysql -h mysql-headless.db.svc.cluster.local -u $DB_USERNAME -p$DB_PASSWORD -e "SELECT 1"; do
                echo "Ждем mysql в namespace db..."
                sleep 5
              done
              echo "MySQL готова"
              echo "Проверка существования базы данных и таблиц..."
              if mysql -h mysql-headless.db.svc.cluster.local -u $DB_USERNAME -p$DB_PASSWORD -e "USE librespeed; SELECT 1 FROM speedtest_users LIMIT 1;" ; then 
                echo "База данных и таблица существуют. Миграции не требуются."
              else
                echo "База данных или таблица не существуют. Выполняем миграции..."
                mysql -h mysql-headless.db.svc.cluster.local -u $DB_USERNAME -p$DB_PASSWORD librespeed < /telemetry_mysql.sql
              fi
          envFrom: # загружаем конфигмап librespeed-env через envFrom
          - configMapRef:
              name: librespeed-env # конфигмап для хранения env-переменных
          - secretRef:
              name: librespeed-secret # секрет для хранения секретных данных
          volumeMounts:
            - name: mysql-sql
              mountPath: /telemetry_mysql.sql
              subPath: telemetry_mysql.sql
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      imagePullSecrets:
        - name: registrysecret # имя секрета
      containers:
      - name: librespeed
        image: registry.rebrainme.com/workshops/middle/kubernetes-local/newplatform_autochecks/speedtest:5.3 # скачивается с закрытого registry
        ports:
          - containerPort: 80
        envFrom: # загружаем конфигмап librespeed-env через envFrom
          - configMapRef:
              name: librespeed-env # конфигмап для хранения env-переменных
          - secretRef:
              name: librespeed-secret # секрет для хранения секретных данных
        volumeMounts:
          - name: servers-volume
            mountPath: /servers.json
            subPath: servers.json
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
      - name: servers-volume
        configMap:
          name: librespeed-servers # имя конфигмапы
      - name: mysql-sql
        configMap:
          name: mysql-sql
